//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<FilterTypes> FilterTypes { get; set; }
        public virtual DbSet<HDDTypes> HDDTypes { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<OSSystems> OSSystems { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual DbSet<ProductTypeFilterAssigns> ProductTypeFilterAssigns { get; set; }
        public virtual DbSet<ProductTypeManufacturerAssigns> ProductTypeManufacturerAssigns { get; set; }
        public virtual DbSet<ProductTypeOSSystemAssigns> ProductTypeOSSystemAssigns { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<ProductTypeStorageAssigns> ProductTypeStorageAssigns { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<ScreenTypes> ScreenTypes { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
    }
}
