//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterTypes
    {
        public FilterTypes()
        {
            this.ProductTypeFilterAssigns = new HashSet<ProductTypeFilterAssigns>();
        }
    
        public int FilterTypeId { get; set; }
        public string FilterType { get; set; }
    
        public virtual ICollection<ProductTypeFilterAssigns> ProductTypeFilterAssigns { get; set; }
    }
}
