//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSystems
    {
        public OSSystems()
        {
            this.PhoneSpecifications = new HashSet<PhoneSpecifications>();
        }
    
        public int OSSystemId { get; set; }
        public string OS { get; set; }
    
        public virtual ICollection<PhoneSpecifications> PhoneSpecifications { get; set; }
    }
}
