//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneSpecifications
    {
        public PhoneSpecifications()
        {
            this.Phones = new HashSet<Phones>();
        }
    
        public int PhoneSpecificationId { get; set; }
        public int ManufacturerId { get; set; }
        public int OSSystemId { get; set; }
        public int Storage { get; set; }
        public int Camera { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual OSSystems OSSystems { get; set; }
        public virtual ICollection<Phones> Phones { get; set; }
    }
}
