//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecifications
    {
        public ProductSpecifications()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ProductSpecificationId { get; set; }
        public int ProductTypeManufacturerAssignId { get; set; }
        public int ProductTypeOSSystemAssignId { get; set; }
        public int ProductTypeStorageAssignId { get; set; }
        public Nullable<int> Camera { get; set; }
        public int ProductTypeId { get; set; }
        public Nullable<int> ScreenTypeId { get; set; }
        public Nullable<int> HDDTypeId { get; set; }
        public Nullable<int> RAMId { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual HDDTypes HDDTypes { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ProductTypeManufacturerAssigns ProductTypeManufacturerAssigns { get; set; }
        public virtual ProductTypeOSSystemAssigns ProductTypeOSSystemAssigns { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual ProductTypeStorageAssigns ProductTypeStorageAssigns { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual ScreenTypes ScreenTypes { get; set; }
    }
}
