//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypes
    {
        public ProductTypes()
        {
            this.ProductSpecifications = new HashSet<ProductSpecifications>();
            this.ProductTypeFilterAssigns = new HashSet<ProductTypeFilterAssigns>();
            this.ProductTypeManufacturerAssigns = new HashSet<ProductTypeManufacturerAssigns>();
            this.ProductTypeOSSystemAssigns = new HashSet<ProductTypeOSSystemAssigns>();
            this.ProductTypeStorageAssigns = new HashSet<ProductTypeStorageAssigns>();
        }
    
        public int ProductTypeId { get; set; }
        public string ProductTypeName { get; set; }
    
        public virtual ICollection<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual ICollection<ProductTypeFilterAssigns> ProductTypeFilterAssigns { get; set; }
        public virtual ICollection<ProductTypeManufacturerAssigns> ProductTypeManufacturerAssigns { get; set; }
        public virtual ICollection<ProductTypeOSSystemAssigns> ProductTypeOSSystemAssigns { get; set; }
        public virtual ICollection<ProductTypeStorageAssigns> ProductTypeStorageAssigns { get; set; }
    }
}
