//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeOSSystemAssigns
    {
        public ProductTypeOSSystemAssigns()
        {
            this.ProductSpecifications = new HashSet<ProductSpecifications>();
        }
    
        public int ProductTypeOSSystemAssignId { get; set; }
        public int ProductTypeId { get; set; }
        public int OSSystemId { get; set; }
    
        public virtual OSSystems OSSystems { get; set; }
        public virtual ICollection<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
